# Generated by Django 5.1.6 on 2025-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_alter_reservation_reservation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default='93E389A8F9', max_length=10, unique=True),
        ),
    ]
